name: Docker Deploy

on:
  push:
    tags: [ '*.*' ]

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      git_tag: ${{ steps.git_info.outputs.tag }}
      git_commit_title: ${{ steps.git_info.outputs.title }}
      git_commit_content: ${{ steps.git_info.outputs.content }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: set-matrix
        run: |
          JSON=$(cat .github/workflows/repo-setting.json | tr '\n' ' ' | sed 's/ //g')
          echo "::set-output name=matrix::$JSON"

      - id: git_info
        run: |
          tag=$(echo ${{ github.ref }} | rev | cut -d/ -f1 | rev)
          echo "::set-output name=tag::$tag"
          title=$(git log -1 --pretty=format:"%s")
          echo "::set-output name=title::$title"
          content=$(git log -1 --pretty=format:"%b")
          echo "::set-output name=content::$content"

  build:
    runs-on: ubuntu-latest
    needs: [ set-matrix ]
    strategy:
      matrix: ${{fromJSON(needs.set-matrix.outputs.matrix)}}

    env:
      id: ${{ secrets[matrix.id] }}
      token: ${{ secrets[matrix.token] }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ matrix.name }}
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ matrix.register }}
          username: ${{ env.id }}
          password: ${{ env.token }}

      - name: Set Up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build and Push ${{ matrix.name }}
        run: |
          make buildx REPO=${{ matrix.push_link }} VERSION=${{ needs.set-matrix.outputs.git_tag }}
